apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellok8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hellok8s
  template:
    metadata:
      labels:
        app: hellok8s
    spec:
      containers:
        - image: mmerts/hellok8s:buggy # Adding a buggy version
          name: hellok8s-container
          readinessProbe:
            periodSeconds: 1
            successThreshold: 5
            httpGet:
              path: /
              port: 4567
